In [1]:
import json
import matplotlib.pyplot as plt
import pandas as pd
import sys
import os
import numpy as np
import math

In [2]:
df2 = pd.read_csv('q1.csv')

In [3]:
df2

,Country,GHRP,Income classification according to WB,Net_ODA_received_perc_of_GNI,Aid dependence,Volume of remittances in USD as a proportion of total GDP percent 2014-18,Remittances,Food imports percent of total merchandise exports,food import dependence,Fuels ores and metals exports percent of total merchandise exports,...,General government gross debt Percent of GDP 2019,Government indeptedness,Total reserves in months of imports 2018,Foreign currency reserves,"Foreign direct investment, net inflows percent of GDP",Foreign direct investment,Covid_19_Economic_exposure_index,Covid_19_Economic_exposure_index_Ex_aid_and_FDI,Covid_19_Economic_exposure_index_Ex_aid_and_FDI_and_food_import,Cities
0,Liechtenstein,No,HIC,No data,x,No data,x,x,x,x,...,x,x,x,x,x,x,x,x,x,"{""Country"":""Liechtenstein"",""City"":""Balzers"",""L..."
1,Eritrea,No,LIC,No data,x,No data,x,x,x,x,...,"165,1","10,0",x,x,x,x,"10,0","10,0","10,0","{""Country"":""Eritrea"",""City"":""Abacheri"",""Latitu..."
2,Bahrain,No,HIC,No data,x,No data,x,"9,4","3,7","76,2",...,"101,7","10,0","0,88","10,0","0,29","0,1","6,3","7,5","8,5","{""Country"":""Bahrain"",""City"":""Abu Baham"",""Latit..."
3,Bahamas,No,HIC,No data,x,No data,x,"19,3","7,7",x,...,"61,5","5,2",x,x,"3,96","1,6","6,1","7,6","7,6","{""Country"":""Bahamas"",""City"":""Abercorn"",""Latitu..."
4,Cyprus,No,HIC,No data,x,"1,83","0,0","12,9","5,2","45,8",...,"96,1","9,5","0,26","10,0","20,86","8,3","7,0","6,7","7,0","{""Country"":""Cyprus"",""City"":""Abesa"",""Latitude"":..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,Djibouti,No,MIC,"7,33","1,2","3,22","0,0",x,x,"0,7",...,"47,4","3,4",x,x,"8,97","3,6","1,4","0,9","0,9","{""Country"":""Djibouti"",""City"":""Adi Adda"",""Latit..."
185,Turkmenistan,No,MIC,"0,08","0,0","0,00","0,0",x,x,x,...,"30,3","1,3",x,x,"4,87","1,9","0,8","0,7","0,7","{""Country"":""Turkmenistan"",""City"":""Aadzi"",""Lati..."
186,Micronesia,No,MIC,"25,08","10,0","7,05","1,0",x,x,x,...,"18,5","0,0",x,x,x,x,"3,7","0,5","0,5","{""Country"":""Micronesia"",""City"":""Adevue"",""Latit..."
187,Afghanistan,Yes,LIC,"19,37","7,2","1,99","0,0","32,3","10,0","11,6",...,"7,5","0,0","12,19","0,0","0,62","0,2","2,4","2,0","0,4","{""Country"":""Afghanistan"",""City"":""`Aaqadari Yos..."
188,Palau,No,HIC,"7,87","1,4","0,79","0,0","22,8","9,1","2,6",...,x,x,x,x,"7,57","3,0","2,8","3,1","0,2","{""Country"":""Palau"",""City"":""Aakip"",""Latitude"":7..."

In [4]:
list(df2)

['Country',
 'GHRP',
 'Income classification according to WB',
 'Net_ODA_received_perc_of_GNI',
 'Aid dependence',
 'Volume of remittances in USD as a proportion of total GDP percent 2014-18',
 'Remittances',
 'Food imports percent of total merchandise exports',
 'food import dependence ',
 'Fuels ores and metals exports percent of total merchandise exports',
 'primary commodity export dependence',
 'tourism as percentage of GDP',
 'tourism dependence',
 'General government gross debt Percent of GDP 2019',
 'Government indeptedness',
 'Total reserves in months of imports 2018',
 'Foreign currency reserves',
 'Foreign direct investment, net inflows percent of GDP',
 'Foreign direct investment',
 'Covid_19_Economic_exposure_index',
 'Covid_19_Economic_exposure_index_Ex_aid_and_FDI',
 'Covid_19_Economic_exposure_index_Ex_aid_and_FDI_and_food_import',
 'Cities']

In [25]:
df2["avg_latitude"] = np.nan
df2["avg_longitude"] = np.nan

i = 0

while i < 189:
    
    latitude_list=[]
    longitude_list=[]
    json_string = df2.iloc[i]['Cities'].split("|||")
    for token in json_string:
        a_json = json.loads(token)
        latitude_list.append(a_json["Latitude"])
        longitude_list.append(a_json["Longitude"])
    mean_latitude = np.mean(latitude_list)
    mean_longitude = np.mean(longitude_list)
    df2.iloc[i]["avg_latitude"] = mean_latitude
    df2.iloc[i]["avg_longitude"] = mean_longitude
    i+=1

df2

,Country,GHRP,Income classification according to WB,Net_ODA_received_perc_of_GNI,Aid dependence,Volume of remittances in USD as a proportion of total GDP percent 2014-18,Remittances,Food imports percent of total merchandise exports,food import dependence,Fuels ores and metals exports percent of total merchandise exports,...,Total reserves in months of imports 2018,Foreign currency reserves,"Foreign direct investment, net inflows percent of GDP",Foreign direct investment,Covid_19_Economic_exposure_index,Covid_19_Economic_exposure_index_Ex_aid_and_FDI,Covid_19_Economic_exposure_index_Ex_aid_and_FDI_and_food_import,Cities,avg_latitude,avg_longitude
0,Liechtenstein,No,HIC,No data,x,No data,x,x,x,x,...,x,x,x,x,x,x,x,"{""Country"":""Liechtenstein"",""City"":""Balzers"",""L...",7.422344,134.510211
1,Eritrea,No,LIC,No data,x,No data,x,x,x,x,...,x,x,x,x,"10,0","10,0","10,0","{""Country"":""Eritrea"",""City"":""Abacheri"",""Latitu...",7.422344,134.510211
2,Bahrain,No,HIC,No data,x,No data,x,"9,4","3,7","76,2",...,"0,88","10,0","0,29","0,1","6,3","7,5","8,5","{""Country"":""Bahrain"",""City"":""Abu Baham"",""Latit...",7.422344,134.510211
3,Bahamas,No,HIC,No data,x,No data,x,"19,3","7,7",x,...,x,x,"3,96","1,6","6,1","7,6","7,6","{""Country"":""Bahamas"",""City"":""Abercorn"",""Latitu...",7.422344,134.510211
4,Cyprus,No,HIC,No data,x,"1,83","0,0","12,9","5,2","45,8",...,"0,26","10,0","20,86","8,3","7,0","6,7","7,0","{""Country"":""Cyprus"",""City"":""Abesa"",""Latitude"":...",7.422344,134.510211
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,Djibouti,No,MIC,"7,33","1,2","3,22","0,0",x,x,"0,7",...,x,x,"8,97","3,6","1,4","0,9","0,9","{""Country"":""Djibouti"",""City"":""Adi Adda"",""Latit...",7.422344,134.510211
185,Turkmenistan,No,MIC,"0,08","0,0","0,00","0,0",x,x,x,...,x,x,"4,87","1,9","0,8","0,7","0,7","{""Country"":""Turkmenistan"",""City"":""Aadzi"",""Lati...",7.422344,134.510211
186,Micronesia,No,MIC,"25,08","10,0","7,05","1,0",x,x,x,...,x,x,x,x,"3,7","0,5","0,5","{""Country"":""Micronesia"",""City"":""Adevue"",""Latit...",7.422344,134.510211
187,Afghanistan,Yes,LIC,"19,37","7,2","1,99","0,0","32,3","10,0","11,6",...,"12,19","0,0","0,62","0,2","2,4","2,0","0,4","{""Country"":""Afghanistan"",""City"":""`Aaqadari Yos...",7.422344,134.510211
188,Palau,No,HIC,"7,87","1,4","0,79","0,0","22,8","9,1","2,6",...,x,x,"7,57","3,0","2,8","3,1","0,2","{""Country"":""Palau"",""City"":""Aakip"",""Latitude"":7...",7.422344,134.510211

###### df2.iloc[5]['Cities']

In [7]:
head = ['Country', 'City', 'Latitude', 'Longitude', 'Population']
json_df = pd.DataFrame(columns=head)
list_df = []
for token in json_string:
    a_json = json.loads(token)
    df_json = pd.DataFrame.from_dict(a_json, orient='index').T
    list_df.append(df_json)

json_df = pd.concat(list_df, ignore_index=True)

print(json_df)

          Country                    City   Latitude Longitude Population
0   Liechtenstein                 Balzers  47.066667       9.5     4447.0
1   Liechtenstein                 Bendern  47.216667       9.5       None
2   Liechtenstein                 Blanken  47.183333  9.533333       None
3   Liechtenstein                 Ebaholz      47.15  9.516667       None
4   Liechtenstein                Ebenholz      47.15  9.516667       None
5   Liechtenstein                  Eschen  47.216667  9.516667     4008.0
6   Liechtenstein                  Gaflei  47.133333  9.533333       None
7   Liechtenstein                 Gambrin  47.216667       9.5       None
8   Liechtenstein         Gamprin-Bendern  47.216667       9.5       None
9   Liechtenstein                 Gamprin  47.216667       9.5     1268.0
10  Liechtenstein   Hinterer Schellenberg  47.233333  9.533333       None
11  Liechtenstein      Hinterschellenberg  47.233333  9.533333       None
12  Liechtenstein     Hinter-Schellenberg  47.233333  9.533333       None
13  Liechtenstein                    Mäls      47.05       9.5       None
14  Liechtenstein                Masescha  47.133333  9.533333       None
15  Liechtenstein                  Mauern  47.216667  9.533333       None
16  Liechtenstein                  Mauren  47.216667  9.533333     3626.0
17  Liechtenstein  Mittlerer Schellenberg  47.233333  9.533333       None
18  Liechtenstein     Mittlerschellenberg  47.233333  9.533333       None
19  Liechtenstein    Mittler-Schellenberg  47.233333  9.533333       None
20  Liechtenstein                Möliholz      47.15       9.5       None
21  Liechtenstein               Mühleholz      47.15       9.5       None
22  Liechtenstein                 Nendeln       47.2      9.55       None
23  Liechtenstein                 Planken  47.183333  9.533333      377.0
24  Liechtenstein                Rotaboda     47.125  9.533333       None
25  Liechtenstein              Rotenboden     47.125  9.533333       None
26  Liechtenstein                  Rugell  47.233333  9.516667       None
27  Liechtenstein                 Ruggell  47.233333  9.516667     1862.0
28  Liechtenstein                  Schaan  47.166667       9.5     5748.0
29  Liechtenstein              Schaanwald  47.216667  9.566667       None
30  Liechtenstein                   Schan  47.166667       9.5       None
31  Liechtenstein            Schellenberg  47.233333  9.533333     1004.0
32  Liechtenstein                   Silum  47.133333      9.55       None
33  Liechtenstein                   Sücka  47.116667  9.566667       None
34  Liechtenstein             Triesenberg  47.116667  9.533333     2689.0
35  Liechtenstein                 Triesen       47.1  9.533333     4701.0
36  Liechtenstein                   Vaduz  47.133333  9.516667     5197.0
37  Liechtenstein   Vorderer Schellenberg  47.233333  9.533333       None
38  Liechtenstein      Vorderschellenberg  47.233333  9.533333       None
39  Liechtenstein     Vorder-Schellenberg  47.233333  9.533333       None
40  Liechtenstein              Wangerbärg       47.1  9.533333       None
41  Liechtenstein              Wangerberg       47.1  9.533333       None

In [33]:
# head = ['Country', 'City', 'Latitude', 'Longitude', 'Population']
# json_df = pd.DataFrame(columns=head)
i = 0
result = []

list_df = []
json_string = df2.iloc[27]['Cities'].split("|||")
print(json_string)
for token in json_string:
    a_json = json.loads(token)
    df_json = pd.DataFrame.from_dict(a_json, orient='index').T
    list_df.append(df_json)

json_df = pd.concat(list_df, ignore_index=True)
copy = json_df.drop(['City','Population'], axis=1)
# df_num = copy[['Latitude', 'Longitude']].astype(str).astype(float)
df = copy.astype({"Latitude": float, "Longitude": float})
df_mean = df.groupby(['Country'])['Latitude', 'Longitude'].mean()
result.append(df_mean)
    
# final = pd.concat(result, ignore_index=True)
# df2.merge(df_mean, on='Country')
# df2

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

In [30]:
df_mean

      Latitude   Longitude
0    47.177778    9.525397
1    15.098916   39.047179
2    26.166726   50.554938
3    24.563413  -76.346703
4    35.044666   33.168091
..         ...         ...
184  11.631813   42.854261
185  38.608539   60.211970
186   8.173096  147.272560
187  34.046741   67.266813
188   7.422344  134.510211

[189 rows x 2 columns]

In [31]:
final.to_csv('lat_log.csv')